version: '3'
services:
  kosmos-webapp:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/kosmos-webapp
    ports:
      - '5000:80'
  graph-server-default:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/graph-server
    ports:
      - '7500:8080'
    environment:
      - quarkus.neo4j.encrypted=true
      - quarkus.neo4j.uri=bolt://${GRAPH_DATABASE_HOST}
      - quarkus.neo4j.authentication.username=${GRAPH_DATABASE_USERNAME}
      - quarkus.neo4j.authentication.password=${GRAPH_DATABASE_PASSWORD}
      - quarkus.log.level=DEBUG
      - kosmos.disable.authorization=true
      - quarkus.oidc.auth-server-url=https://self.se.jku.at/realms/se-mitarbeiter
    labels:
      - "datacontainer=yes"
      - "datacontainerId=default"
  visualization-service:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/visualization-service
    ports:
      - '7600:3000'
    environment:
      - DATA_PROCESSING_SERVICE=http://data-processing-service:3000
      - DATABASE_USER=${KOSMOS_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${KOSMOS_DATABASE_PASSWORD}
      - DATABASE_HOST=${KOSMOS_DATABASE_HOST}
      - DATABASE_PORT=443
      - DATABASE_PROTOCOL=bolt+s
      - KC_ENABLED=false
      - KC_AUTH_SERVER_URL=https://self.se.jku.at/auth
  datacontainermanagement-service:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/datacontainermanagement-service
    ports:
      - '7700:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=3000
      - KOSMOS_DOCKER_NETWORK=kosmos_default
      - DOCKER_SOCKETPATH=/var/run/docker.sock
      - GRAPH_SERVER_PREFIX=graph-server
      - GRAPH_SERVER_PORT=8080
      - GRAPH_SERVER_DOCKER_IMAGE=kosmos_graph-server-default
      - GRAPH_SERVER_NAME_PREFIX=graph-server
      - GRAPH_SERVER_LOG_LEVEL=DEBUG
      - GRAPH_DATABASE_DOCKER_IMAGE=kosmos_graph-database-default
      - GRAPH_DATABASE_NAME_PREFIX=graph-database
      - GRAPH_DATABASE_USERNAME=neo4j
      - GRAPH_DATABASE_PASSWORD=Gute$$Pa55wort
      - GRAPH_DATBASE_VOLUME_PREFIX=graph-volume
      - GRAPH_DATBASE_USE_VOLUME=true
      - MONGO_URL=mongodb://${MONGO_DATABASE_USERNAME}:${MONGO_DATABASE_PASSWORD}@${MONGO_DATABASE_HOST}/${MONGO_DATABASE_NAME}?tls=true
      - DATARETRIEVER_HOST=http://dataretriever-service:3000
      - KC_ENABLED=false
      - KC_AUTH_SERVER_URL=https://self.se.jku.at/auth
  data-processing-service:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/data-processing-service
    ports:
      - '8100:3000'
    environment:
      - SNAPSHOT_SERVICE=http://kosmos-mongo-services:8080/
      - EXPERTQUERY_SERVICE=http://kosmos-services:8080/
      - DATABASE_USER=${KOSMOS_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${KOSMOS_DATABASE_PASSWORD}
      - DATABASE_HOST=${KOSMOS_DATABASE_HOST}
      - DATABASE_PORT=443
      - DATABASE_PROTOCOL=bolt+s
      - KC_ENABLED=false
      - KC_AUTH_SERVER_URL=https://self.se.jku.at/auth
  kosmos-services:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/kosmos-services
    ports:
      - '7400:8080'
    environment:
      - quarkus.neo4j.encrypted=true
      - quarkus.neo4j.uri=bolt://${KOSMOS_DATABASE_HOST}
      - quarkus.neo4j.authentication.username=${KOSMOS_DATABASE_USERNAME}
      - quarkus.neo4j.authentication.password=${KOSMOS_DATABASE_PASSWORD}
      - DATACONTAINER_MANAGEMENT_HOST=http://datacontainermanagement-service:3000
      - SNAPSHOT_SERVICE_HOST=http://kosmos-mongo-services:8080
      - kosmos.disable.authorization=true
      - quarkus.oidc.auth-server-url=https://self.se.jku.at/realms/se-mitarbeiter
      - quarkus.oidc-client.auth-server-url=https://self.se.jku.at/realms/se-mitarbeiter
  kosmos-mongo-services:
    image: registry.gitlab.com/jku-se/kosmos-quickstart/kosmos-mongo-services
    ports:
      - '7450:8080'
    environment:
      - kosmos.disable.authorization=true
      - quarkus.oidc.auth-server-url=https://self.se.jku.at/realms/se-mitarbeiter
      - quarkus.oidc-client.auth-server-url=https://self.se.jku.at/realms/se-mitarbeiter
      - quarkus.mongodb.connection-string=mongodb://${MONGO_DATABASE_USERNAME}:${MONGO_DATABASE_PASSWORD}@${MONGO_DATABASE_HOST}/${MONGO_DATABASE_NAME}?tls=true
      - quarkus.mongodb.database=${MONGO_DATABASE_NAME}
      - quarkus.mongodb.credentials.username=${MONGO_DATABASE_USERNAME}
      - quarkus.mongodb.credentials.password=${MONGO_DATABASE_PASSWORD}